# 通用response响应缺少参数
LACK_NUM = 3
COMMON_CODE = 1001

# 配置参数接口
VERSION = '1.1.1'
FILE_NAME = 'https://imtt.dd.qq.com/16891/F14AE2A255D126C3D3699AE14A856990.apk'
CONFIG_DATA_LENGTH = 4

# 升级更新接口
VERSION_UP = '1.1.1'
FILE_ADDR = 'https://imtt.dd.qq.com/16891/F14AE2A255D126C3D3699AE14A856990.apk'
UP_DATA_LENGTH = 4

# 购买页
BUY_Z_CODE = 1001
BUY_DATA_LENGTH = 5
JD = 'http://www.jd.com'
TB = 'http://www.taobao.com/'

# 全国城市列表
CITY_DATA_LENGTH = 22

# 又拍云上传签名
SIGN_DATA_LENGTH = 3

# 计费商品列表
IMG_PRICE = 10
WATER_MARK_PRICE = 990
WATER_Z_MARK_PRICE = 1990
PHONE_PRICE  = 990
PSD_PRICE = 1990
GOODS_DATA_LENGTH = 5

# 活动列表页
ACTIVITY_DATA_LENGTH = 29

# 活动资料页
ACTIVITYDATA_LENGTH = 35

# 摄影师管理页
CAMERIST_DATA_LENGTH = 5

# 直播原相册
PICTURE_ALBUM_ID = 1032
PICTUREALBUM_DATA_LENGTH = 5

# 直播详情
PICTURE_DETAIL_ID = 1032
PICTUREDETAIL_LENGTH = 3

# 用户已上传的图片列表
USER_PICTURE_ID = 1032
USER_PICTURE_COUNT = '0'
USERPICTURE_DATA_LENTH = 3

# 导播管理界面
EDITOR_LIST_ID = 1032
EDITORLIST_DATA_LENGTH = 2

# 编辑室列表
EDIT_LIST_TYPE = 0
EDITLIST_DATA_LENGTH = 3

# 直播预约摄影师列表
RESERVELIST_DATA_LENGTH = 0

# 直播预sn
PREP_DATA_LENGTH = 1

# 分类列表
CATEGORY_DATA_LENGTH = 4

# 我预约别人的
USERMYBOOK_DATA_LENGTH = 0

# 别人预约我的
USERMYCUST_DATA_LENGTH = 0

# 我关注的列表
USERSUBSCRIBE_DATA_LENGTH = 3

# 分享加强版
SHARE_ID = 1032
SHARE_TYPE = 2
SHARE_DATA_LENGTH = 8

# 消息列表
USER_MESSAGE_PAGE = 0
USER_MESSAGE_PERNUM = 0
MESSAGE_DATA_LENGTH = 0

# banner
BANNER_DATA_LENGTH = 1